Remove CentOS Stream 8
osuosl-cookbooks/osl-php pull request #62
Opened 2023-05-01 19:54 UTC by ArtofBugs

2023-05-01 20:01 UTC, ramereth requested changes
Please remove/update CentOS 8 spec test references.

2023-05-03 19:51 UTC, ramereth requested changes

2023-05-03 19:51 UTC, ramereth commented on recipes/apc.rb
> +ruby_block 'raise_almalinux8_exception' do
Let's just generalize this as `el` in case we move to something else down the road.
```suggestion
ruby_block 'raise_el8_exception' do
```

2023-05-03 19:51 UTC, ramereth commented on recipes/apc.rb
> +    raise 'APC is not compatible with Almalinux 8.'
```suggestion
    raise 'APC is not compatible with EL 8.'
```

2023-05-03 19:51 UTC, ramereth commented on recipes/packages.rb
> +# pecl-imagick is not available on AlmaLinux 8
```suggestion
# pecl-imagick is not available on EL 8
```

2023-05-04 18:12 UTC, ArtofBugs commented
!bump patch ~

2023-05-04 18:12 UTC, merged